### ISSUE TITLE
PVT V2 implementation

### ISSUE THREAD

**Issue by khawar-islam** [DengPingFan/Polyp-PVT#2]
Hi @DengPingFan 

Did you check the implementation of PVT V2? Actually, I need a classification head in forward propagation to apply some loss functions in classification HEAD. Unfortunately, you comment out this line. Could you please tell me the solution to this problem?

**Comment by dongbo811** [comment]
Hello, PVT v2 provides a complete code for classification. Please refer to: https://github.com/whai362/PVT
