### ISSUE TITLE
Sincerely request the thesis baseline code

### ISSUE THREAD

**Issue by jue12345** [DengPingFan/Polyp-PVT#4]
Hi, thank you for your excellent work.
The baseline you used for comparison in your paper is from "Pvtv2: Improved baselines with pyramid vision transformer", which I have tried many times without success. I didn't find this part of the code in the project. Could you provide a baseline code of PVTV2 that you use?
Thanks!

**Comment by DengPingFan** [comment]
PVT-v2: https://github.com/whai362/PVT
