### ISSUE TITLE
About CFM module

### ISSUE THREAD

**Issue by Zhiyang-Xu** [DengPingFan/Polyp-PVT#5]
CFM module is similar to the partial decoder module

**Comment by DengPingFan** [comment]
Hi, 

Yes. It is similar to the CPD. Note that the Polyp-PVT model is just a technique report to show how to introduce the PVT backbone.  You can update some key components to achieve your own goal. 

Best,

**Comment by Zhiyang-Xu** [comment]
Understand. Thank you for your work.
